version: "3.8"

services:
  ups_pickup:
    build: .
    env_file:
      - app/.env
    volumes:
      - ./data:/app/data
    ports:
      - "5000:5000"
    command: ["python", "app.py"]

  # ups_sync:
  #   build: .
  #   volumes:
  #     - ./data:/app/data

  # db:
  #   image: postgres:14
  #   restart: always
  #   environment:
  #     POSTGRES_DB: upsdb
  #     POSTGRES_USER: upsuser
  #     POSTGRES_PASSWORD: upspass
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata: